### ISSUE TITLE
Async gem dependency breaks turbo_test

### ISSUE THREAD

**Issue by kgreunke** [ioquatix/turbo_test#9]
This commit in the `async-io` gem  https://github.com/socketry/async-io/commit/2fe9ed29c91db843e2911032fa929123bd4ab024 breaks turbo test with the following error

```
/Users/karl/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/turbo_test-0.1.2/bin/turbo_test:30:in `rescue in <top (required)>': undefined method `logger' for Async:Module (NoMethodError)

        Async.logger.error(TurboTest::Command) {error}
             ^^^^^^^
        from /Users/karl/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/turbo_test-0.1.2/bin/turbo_test:25:in `<top (required)>'
        from bin/turbo_test:29:in `load'
        from bin/turbo_test:29:in `<main>'
/Users/karl/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/turbo_test-0.1.2/lib/turbo_test/command/run.rb:48:in `call': undefined method `logger' for Async:Module (NoMethodError)

                                Async.logger.info(self) do |buffer|
                                     ^^^^^^^
        from /Users/karl/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/turbo_test-0.1.2/lib/turbo_test/command/top.rb:57:in `call'
        from /Users/karl/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/samovar-2.1.4/lib/samovar/command.rb:36:in `call'
        from /Users/karl/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/turbo_test-0.1.2/lib/turbo_test/command.rb:30:in `call'
        from /Users/karl/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/turbo_test-0.1.2/bin/turbo_test:26:in `<top (required)>'
        from bin/turbo_test:29:in `load'
        from bin/turbo_test:29:in `<main>'
```
  

For anybody that finds this before it's fixed. Pinning the `async` gem to `< 2` fixes the problem in rails.  Also, monkeypatching the `Async` class to add the `Async#logger` method also fixes the issue by putting this in the binstub (also in rails, but I'd imagine it would work elsewhere too)

```
require 'async'

module TurboTestBugFix
  def logger
    Console.logger
  end
end
unless Async.respond_to?(:logger)
  Async.extend(TurboTestBugFix)
end
```

**Comment by ioquatix** [comment]
Fixed.

**Comment by kgreunke** [comment]
Thanks for the fix!
